name: CI
on:
  push:
    branches:
      - main #here we choose to deploy only when a push is detected on the main branch

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: gabrielfalcao/pyenv-action@v7
      with: 
        default: 3.8.6
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1 # Use your bucket region here

    # - name: create environment
    #   run: pyenv local 3.8.6 && python -mvenv .venv386

    # Here you could add some building steps if you were dealing with some angular/react/Vue...
    - name: Build static site
      run: pip install -r requirements.txt && cd ./notes && mkdocs build

    # Deploy to aws, --delete flag will remove any file in S3 bucket that are not in the deployed folder 
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./notes/site s3://notes.fdlme.com --delete
      